name: cifar10_tabular
defaults:
    - feeder@params.feeder_args: cumulative_static
    - splitter@params.splitter_args: random
params:
    batch_size: 32
    data_dir: data/cifar10_tabular/cifar10_tabular.arff