name: fairface
defaults:
    - feeder@params.feeder_args: cumulative_static
    - splitter@params.splitter_args: random
params:
    batch_size: 32
    data_dir: data/fairface/processed
    task: "gender"