experiment_name: model_saving
defaults:
    - callback: model_saving
    - data_module: adult
    - experiment: model_saving
    - inferer: standard
    - model: mlp
    - module: standard
    - threshold_selector: naive
    - trainer: pytorch
hydra:
    run:
        dir: results/${data_module.name}/${model.name}/${experiment_name}/${wandb_run:}
    output_subdir: .