experiment_name: noise_by_dichotomous_difficulty
counts_path: 39403910.csv
defaults:
    - callback: default
    - data_module: adult
    - experiment: noise_by_dichotomous_difficulty
    - label_corruptor: uniform_noise
    - model: mlp
    - module@original_module: standard
    - module@update_module: standard
    - threshold_selector: naive
    - trainer@original_trainer: pytorch
    - trainer@update_trainer: pytorch
hydra:
    run:
        dir: results/${data_module.name}/${model.name}/noise_by_dichotomous_difficulty/${experiment.seed}
    output_subdir: .