experiment_name: prediction_extraction
defaults:
    - callback: default
    - data_module: adult
    - experiment: prediction_extraction
    - inferer: standard
    - model: mlp
    - module: standard
    - threshold_selector: naive
    - trainer: pytorch
hydra:
    run:
        dir: results/${data_module.name}/${model.name}/${experiment_name}/${wandb_run:}
    output_subdir: .