experiment_name: update_pipeline
defaults:
    - callback@original_callback: default
    - callback@update_callback: default
    - data_module: adult
    - experiment: update_pipeline
    - inferer@input_inferer: input
    - inferer@prediction_inferer: prediction
    - input_corruptor: clean
    - label_corruptor: clean
    - model: mlp
    - module@original_module: standard
    - module@update_module: standard
    - trainer@original_trainer: pytorch
    - trainer@update_trainer: pytorch
hydra:
    run:
        dir: results/${data_module.name}/${model.name}/${experiment_name}/${wandb_run:}
    output_subdir: .